### ISSUE TITLE
Unreadable text in certain popovers

### ISSUE THREAD

**Issue by mathiascode** [MX-Linux/mx-comfort-themes#6]
Certain popovers, such as the emoji selector (right-click any text entry -> Insert Emoji) or popovers containing a treeview widget, are unreadable:

![image](https://github.com/nicotine-plus/nicotine-plus/assets/88614182/ac7b2a27-32b0-42c1-ae4f-ae675e3e91af)

This seems to be the problematic line in the CSS: https://github.com/MX-Linux/mx-comfort-themes/blob/b8855ac3e70a8c5a86ab504bba9b6a9e6e709777/mx-comfort/gtk-3.0/dist/gtk.css#L4197

Changing 1.3 to 0.3 results in the following background color:

![](https://github.com/nicotine-plus/nicotine-plus/assets/8754153/a0226871-5237-469f-8361-d1cf613e0b91)

I'm not sure if this is the intended background/text color though.

**Comment by dolphinoracle** [comment]
thank you this fixes a couple of problems in some apps, especially foliate

**Comment by mathiascode** [comment]
Thanks for the quick response! Could you update the GTK 4 theme as well?
